name: Daily Super Bot
on: 
  push: #когда будет выполнять пуш - выполняется скрипт

jobs: #что нужно делать
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Run script
        run: python main.py

